{
gROOT->ProcessLine(".L ${ARA_UTIL_INSTALL_DIR}lib/libAraEvent.so")
gROOT->ProcessLine(".L ${ARA_UTIL_INSTALL_DIR}lib/libAraDisplay.so")
gROOT->ProcessLine(".L ${ARA_UTIL_INSTALL_DIR}lib/libAraCorrelator.so")
gROOT->ProcessLine(".L ${ARA_UTIL_INSTALL_DIR}lib/libAraVertex.so")
gROOT->ProcessLine(".L ${ARA_UTIL_INSTALL_DIR}lib/libRootFftwWrapper.so")
gROOT->ProcessLine(".L ${ARA_UTIL_INSTALL_DIR}lib/libAraConfig.so")

gROOT->ProcessLine('#include "${ARA_UTIL_INSTALL_DIR}/../source/AraSim/EarthModel.h"')
gROOT->ProcessLine('#include "${ARA_UTIL_INSTALL_DIR}/../source/AraSim/Event.h"')
gROOT->ProcessLine('#include "${ARA_UTIL_INSTALL_DIR}/../source/AraSim/Spectra.h"')    
gROOT->ProcessLine('#include "${ARA_UTIL_INSTALL_DIR}/../source/AraSim/IceModel.h"')
gROOT->ProcessLine('#include "${ARA_UTIL_INSTALL_DIR}/../source/AraSim/Position.h"')
gROOT->ProcessLine('#include "${ARA_UTIL_INSTALL_DIR}/../source/AraSim/Report.h"')
gROOT->ProcessLine('#include "${ARA_UTIL_INSTALL_DIR}/../source/AraSim/Detector.h"')
gROOT->ProcessLine('#include "${ARA_UTIL_INSTALL_DIR}/../source/AraSim/Settings.h"')
    
gROOT->ProcessLine('#include "/cvmfs/ara.opensciencegrid.org/trunk/centos7/source/libRootFftwWrapper/include/FFTtools.h"')
gROOT->ProcessLine('#include "${ARA_UTIL_INSTALL_DIR}include/AraGeomTool.h"')
gROOT->ProcessLine('#include "${ARA_UTIL_INSTALL_DIR}include/RayTraceCorrelator.h"')
gROOT->ProcessLine('#include "${ARA_UTIL_INSTALL_DIR}include/RawAtriStationEvent.h"')
gROOT->ProcessLine('#include "${ARA_UTIL_INSTALL_DIR}include/RawAraStationEvent.h"')
gROOT->ProcessLine('#include "${ARA_UTIL_INSTALL_DIR}include/RawAraGenericHeader.h"')
gROOT->ProcessLine('#include "${ARA_UTIL_INSTALL_DIR}include/RawAtriStationBlock.h"')
gROOT->ProcessLine('#include "${ARA_UTIL_INSTALL_DIR}include/AraEventCalibrator.h"')
gROOT->ProcessLine('#include "${ARA_UTIL_INSTALL_DIR}include/UsefulIcrrStationEvent.h"')
gROOT->ProcessLine('#include "${ARA_UTIL_INSTALL_DIR}include/UsefulAtriStationEvent.h"')
}
